# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: capistrano-monit_runit 3.0.4 ruby lib

Gem::Specification.new do |s|
  s.name = "capistrano-monit_runit"
  s.version = "3.0.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Leif Ringstad"]
  s.date = "2015-08-13"
  s.description = "Helpers for capistrano recipes using runit/monit."
  s.email = "leifcr@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "capistrano-monit_runit.gemspec",
    "lib/capistrano/base.rb",
    "lib/capistrano/capistrano-monit_runit.rb",
    "lib/capistrano/dsl/base_paths.rb",
    "lib/capistrano/dsl/monit_paths.rb",
    "lib/capistrano/dsl/runit_paths.rb",
    "lib/capistrano/helpers/base.rb",
    "lib/capistrano/helpers/monit.rb",
    "lib/capistrano/helpers/runit.rb",
    "lib/capistrano/monit.rb",
    "lib/capistrano/runit.rb",
    "lib/capistrano/tasks/base.rake",
    "lib/capistrano/tasks/monit.rake",
    "lib/capistrano/tasks/runit.rake",
    "templates/monit/app_include.conf.erb",
    "templates/monit/monitrc.erb",
    "templates/runit/finish.erb",
    "templates/runit/log_run.erb",
    "templates/runit/run.erb"
  ]
  s.homepage = "https://github.com/leifcr/capistrano-monit_runit"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.6"
  s.summary = "Helpers for capistrano recipes using runit/monit"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<capistrano>, ["~> 3.4"])
      s.add_runtime_dependency(%q<activesupport>, [">= 3.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.7"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0"])
    else
      s.add_dependency(%q<capistrano>, ["~> 3.4"])
      s.add_dependency(%q<activesupport>, [">= 3.0"])
      s.add_dependency(%q<bundler>, ["~> 1.7"])
      s.add_dependency(%q<jeweler>, ["~> 2.0"])
    end
  else
    s.add_dependency(%q<capistrano>, ["~> 3.4"])
    s.add_dependency(%q<activesupport>, [">= 3.0"])
    s.add_dependency(%q<bundler>, ["~> 1.7"])
    s.add_dependency(%q<jeweler>, ["~> 2.0"])
  end
end

