# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: capistrano-monit_runit 3.1.3 ruby lib

Gem::Specification.new do |s|
  s.name = "capistrano-monit_runit".freeze
  s.version = "3.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Leif Ringstad".freeze]
  s.date = "2019-03-30"
  s.description = "Helpers for capistrano recipes using runit/monit.".freeze
  s.email = "leifcr@gmail.com".freeze
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "capistrano-monit_runit.gemspec",
    "lib/capistrano/base.rb",
    "lib/capistrano/capistrano-monit_runit.rb",
    "lib/capistrano/dsl/base_paths.rb",
    "lib/capistrano/dsl/monit_paths.rb",
    "lib/capistrano/dsl/runit_paths.rb",
    "lib/capistrano/helpers/base.rb",
    "lib/capistrano/helpers/monit.rb",
    "lib/capistrano/helpers/runit.rb",
    "lib/capistrano/monit.rb",
    "lib/capistrano/runit.rb",
    "lib/capistrano/tasks/base.rake",
    "lib/capistrano/tasks/monit.rake",
    "lib/capistrano/tasks/runit.rake",
    "templates/monit/app_include.conf.erb",
    "templates/runit/finish.erb",
    "templates/runit/log_run.erb",
    "templates/runit/run.erb"
  ]
  s.homepage = "https://github.com/leifcr/capistrano-monit_runit".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "3.0.3".freeze
  s.summary = "Helpers for capistrano recipes using runit/monit".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<capistrano>.freeze, ["~> 3.4"])
      s.add_runtime_dependency(%q<activesupport>.freeze, [">= 4.0"])
      s.add_development_dependency(%q<bundler>.freeze, ["~> 1.7"])
      s.add_development_dependency(%q<juwelier>.freeze, [">= 0"])
    else
      s.add_dependency(%q<capistrano>.freeze, ["~> 3.4"])
      s.add_dependency(%q<activesupport>.freeze, [">= 4.0"])
      s.add_dependency(%q<bundler>.freeze, ["~> 1.7"])
      s.add_dependency(%q<juwelier>.freeze, [">= 0"])
    end
  else
    s.add_dependency(%q<capistrano>.freeze, ["~> 3.4"])
    s.add_dependency(%q<activesupport>.freeze, [">= 4.0"])
    s.add_dependency(%q<bundler>.freeze, ["~> 1.7"])
    s.add_dependency(%q<juwelier>.freeze, [">= 0"])
  end
end

